### ISSUE TITLE
Fix symbol not found error in ExplicitChecks.mch

### ISSUE THREAD

**Issue by leuschel** [favu100/b2program#17] opened 2022-07-06 13:15 UTC
when commenting in
```
( #(f,y).((f = %x.(x : 0..100|x + y) & y=1000 & f(5) = 1005)) )
```
we get this error

make ExplicitChecks LANGUAGE=java DIRECTORY=benchmarks/model_checking/ProB/Other
java -jar B2Program-all-0.1.0-SNAPSHOT.jar -l java -mc true -f benchmarks/model_checking/ProB/Other/ExplicitChecks.mch
cp benchmarks/model_checking/ProB/Other/*.java .
javac -cp .:btypes.jar ExplicitChecks.java
ExplicitChecks.java:156: error: cannot find symbol
            _ic_set_7 = _ic_set_7.union(new BRelation<BInteger, BInteger>(new BTuple<>(_ic_x_1, _ic_x_1.plus(y))));
                                                                                                             ^
  symbol:   variable y
  location: class ExplicitChecks
1 error

**Comment by favu100** [comment] 2022-07-07 14:54
This should not be possible as the bounded variables are enumerated in the order they are defined. This construct should be detected by the code generator

**Comment by favu100** [comment] 2024-08-19 12:35
This predicate is now allowed by B2Program and the issue is fixed now

**Closed by favu100** 2024-08-19 12:35 UTC
